name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-linux-gnu-as:
    name: Linux with GNU AS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure CMake (GNU AS)
      run: |
        cmake -B build -DUSE_NASM=OFF -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Test example
      run: |
        cd build/example
        ./res_example
        
    - name: Verify output
      run: |
        output=$(cd build/example && ./res_example)
        if [ "$output" != "Hello, world!" ]; then
          echo "Expected 'Hello, world!' but got '$output'"
          exit 1
        fi
        echo "Test passed: Output matches expected result"

  test-linux-nasm:
    name: Linux with NASM
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools and NASM
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake nasm
        
    - name: Configure CMake (NASM)
      run: |
        cmake -B build -DUSE_NASM=ON -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Test example
      run: |
        cd build/example
        ./res_example
        
    - name: Verify output
      run: |
        output=$(cd build/example && ./res_example)
        if [ "$output" != "Hello, world!" ]; then
          echo "Expected 'Hello, world!' but got '$output'"
          exit 1
        fi
        echo "Test passed: Output matches expected result"

  test-windows-msvc-nasm:
    name: Windows (MSVC) with NASM
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      
    - name: Install NASM
      run: |
        choco install nasm
        
    - name: Configure CMake (NASM)
      run: |
        cmake -B build -DUSE_NASM=ON -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Test example
      run: |
        cd build\example\Release
        .\res_example.exe
        
    - name: Verify output
      run: |
        cd build\example\Release
        $output = .\res_example.exe
        if ($output -ne "Hello, world!") {
          Write-Host "Expected 'Hello, world!' but got '$output'"
          exit 1
        }
        Write-Host "Test passed: Output matches expected result"

  test-macos-nasm:
    name: macOS with NASM
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install NASM
      run: |
        brew install nasm
        
    - name: Configure CMake (NASM)
      run: |
        cmake -B build -DUSE_NASM=ON -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Test example
      run: |
        cd build/example
        ./res_example
        
    - name: Verify output
      run: |
        output=$(cd build/example && ./res_example)
        if [ "$output" != "Hello, world!" ]; then
          echo "Expected 'Hello, world!' but got '$output'"
          exit 1
        fi
        echo "Test passed: Output matches expected result"
