name: Extended Testing

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly to catch any dependency issues
    - cron: '0 0 * * 0'

jobs:
  test-matrix:
    name: Test ${{ matrix.os }} with ${{ matrix.assembler }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux configurations
          - os: ubuntu-latest
            assembler: "GNU AS"
            use_nasm: "OFF"
            build_type: "Debug"
            install_cmd: "sudo apt-get update && sudo apt-get install -y build-essential cmake"
          - os: ubuntu-latest
            assembler: "GNU AS"
            use_nasm: "OFF"
            build_type: "Release"
            install_cmd: "sudo apt-get update && sudo apt-get install -y build-essential cmake"
          - os: ubuntu-latest
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Debug"
            install_cmd: "sudo apt-get update && sudo apt-get install -y build-essential cmake nasm"
          - os: ubuntu-latest
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Release"
            install_cmd: "sudo apt-get update && sudo apt-get install -y build-essential cmake nasm"
          
          # Windows configurations
          - os: windows-latest
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Debug"
            install_cmd: ""
          - os: windows-latest
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Release"
            install_cmd: ""            # macOS configurations  
          - os: macos-13  # Use Intel-based runner for NASM compatibility
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Debug"
            install_cmd: "brew install nasm"
          - os: macos-13  # Use Intel-based runner for NASM compatibility
            assembler: "NASM"
            use_nasm: "ON"
            build_type: "Release"
            install_cmd: "brew install nasm"
          - os: macos-latest  # ARM64 runner
            assembler: "GNU AS"
            use_nasm: "OFF"
            build_type: "Debug"
            install_cmd: ""
          - os: macos-latest  # ARM64 runner
            assembler: "GNU AS"
            use_nasm: "OFF"
            build_type: "Release"
            install_cmd: ""
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install dependencies (Linux/macOS)
      if: runner.os != 'Windows'
      run: ${{ matrix.install_cmd }}
      shell: bash
      
    - name: Install NASM (official, Windows)
      if: runner.os == 'Windows' && matrix.use_nasm == 'ON'
      run: |
        $url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-win64.zip"
        $out = "$env:RUNNER_TEMP\nasm.zip"
        Invoke-WebRequest $url -OutFile $out
        Expand-Archive $out -DestinationPath "C:\nasm"
        $nasmDir = Get-ChildItem "C:\nasm" | Where-Object { $_.PSIsContainer } | Select-Object -First 1 -ExpandProperty FullName
        echo "Добавляю $nasmDir в PATH"
        echo "$nasmDir" | Out-File -FilePath $env:GITHUB_PATH -Append
        Get-ChildItem "$nasmDir"
      shell: pwsh

    - name: Show NASM version (Windows)
      if: runner.os == 'Windows' && matrix.use_nasm == 'ON'
      run: nasm.exe -v
      shell: pwsh
        
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows' && matrix.use_nasm != 'ON'
      run: ${{ matrix.install_cmd }}
      shell: pwsh
      

      
    - name: Show versions
      run: |
        echo "=== System Information ==="
        echo "OS: ${{ matrix.os }}"
        echo "Assembler: ${{ matrix.assembler }}"
        echo "Build Type: ${{ matrix.build_type }}"
        echo ""
        echo "=== CMake Version ==="
        cmake --version
        echo ""
        if [ "${{ runner.os }}" = "Linux" ]; then
          echo "=== GCC Version ==="
          gcc --version
          if [ "${{ matrix.use_nasm }}" = "ON" ]; then
            echo ""
            echo "=== NASM Version ==="
            nasm -v
          else
            echo ""
            echo "=== GNU AS Version ==="
            as --version
          fi
        elif [ "${{ runner.os }}" = "Windows" ]; then
          echo "=== MSVC Version ==="
          cl 2>&1 | findstr "Microsoft" || true
          if [ "${{ matrix.use_nasm }}" = "ON" ]; then
            echo ""
            echo "=== NASM Version ==="
            nasm -v
          fi
        elif [ "${{ runner.os }}" = "macOS" ]; then
          echo "=== Clang Version ==="
          clang --version
          echo ""
          echo "=== Architecture ==="
          uname -m
          if [ "${{ matrix.use_nasm }}" = "ON" ]; then
            echo ""
            echo "=== NASM Version ==="
            nasm -v
          fi
        fi
      shell: bash
      
    - name: Configure CMake (Static library)
      run: |
        cmake -B build-static -DUSE_NASM=${{ matrix.use_nasm }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=OFF
        
    - name: Build (Static library)
      run: |
        cmake --build build-static --config ${{ matrix.build_type }}
        
    - name: Test static library example (Unix)
      if: runner.os != 'Windows'
      run: |
        cd build-static/example
        ./res_example
        
    - name: Test static library example (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build-static/example/${{ matrix.build_type }}
        ./res_example.exe
        
    - name: Configure CMake (Shared library)
      run: |
        cmake -B build-shared -DUSE_NASM=${{ matrix.use_nasm }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=ON
        
    - name: Build (Shared library)
      run: |
        cmake --build build-shared --config ${{ matrix.build_type }}
        
    - name: Test shared library example (Unix)
      if: runner.os != 'Windows'
      run: |
        cd build-shared/example
        ./res_example
        
    - name: Test shared library example (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build-shared/example/${{ matrix.build_type }}
        ./res_example.exe
        
    - name: Verify output consistency (Unix)
      if: runner.os != 'Windows'
      run: |
        static_output=$(cd build-static/example && ./res_example)
        shared_output=$(cd build-shared/example && ./res_example)
        expected="Hello, world!"
        
        if [ "$static_output" != "$expected" ]; then
          echo "Static library output mismatch: expected '$expected', got '$static_output'"
          exit 1
        fi
        
        if [ "$shared_output" != "$expected" ]; then
          echo "Shared library output mismatch: expected '$expected', got '$shared_output'"
          exit 1
        fi
        
        if [ "$static_output" != "$shared_output" ]; then
          echo "Static and shared library outputs differ: '$static_output' vs '$shared_output'"
          exit 1
        fi
        
        echo "✅ All tests passed: Output matches expected result"
        
    - name: Verify output consistency (Windows)
      if: runner.os == 'Windows'
      run: |
        cd build-static/example/${{ matrix.build_type }}
        $static_output = (.\res_example.exe | Out-String).Trim()
        cd ../../../build-shared/example/${{ matrix.build_type }}
        $shared_output = (.\res_example.exe | Out-String).Trim()
        $expected = "Hello, world!"
        
        if ($static_output -ne $expected) {
          Write-Host "Static library output mismatch: expected '$expected', got '$static_output'"
          exit 1
        }
        
        if ($shared_output -ne $expected) {
          Write-Host "Shared library output mismatch: expected '$expected', got '$shared_output'"
          exit 1
        }
        
        if ($static_output -ne $shared_output) {
          Write-Host "Static and shared library outputs differ: '$static_output' vs '$shared_output'"
          exit 1
        }
        
        Write-Host "✅ All tests passed: Output matches expected result"

  install-test:
    name: Installation Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-13  # Use Intel-based runner for NASM compatibility
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake nasm
        
    - name: Install NASM (official, Windows)
      if: runner.os == 'Windows'
      run: |
        $url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-win64.zip"
        $out = "$env:RUNNER_TEMP\nasm.zip"
        Invoke-WebRequest $url -OutFile $out
        Expand-Archive $out -DestinationPath "C:\nasm"
        $nasmDir = Get-ChildItem "C:\nasm" | Where-Object { $_.PSIsContainer } | Select-Object -First 1 -ExpandProperty FullName
        echo "Добавляю $nasmDir в PATH"
        echo "$nasmDir" | Out-File -FilePath $env:GITHUB_PATH -Append
        Get-ChildItem "$nasmDir"
      shell: pwsh

    - name: Show NASM version (Windows)
      if: runner.os == 'Windows'
      run: nasm.exe -v
      shell: pwsh
        
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install nasm
        
    - name: Configure and install
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
        cmake --build build --config Release
        cmake --install build --config Release
        
    - name: Verify installation (Unix)
      if: runner.os != 'Windows'
      run: |
        ls -la install/
        find install/ -name "*.h" -o -name "*.cmake" -o -name "*.a" -o -name "*.lib" -o -name "*.so" -o -name "*.dll" | head -20
        
    - name: Verify installation (Windows)
      if: runner.os == 'Windows'
      run: |
        Get-ChildItem -Recurse install/ | Format-Table -AutoSize
        Get-ChildItem -Recurse install/ -Include "*.h", "*.cmake", "*.a", "*.lib", "*.so", "*.dll" | Select-Object -First 20 | Format-Table Name, FullName -AutoSize
      shell: pwsh
